# Generated by Django 4.2.5 on 2023-09-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Letter",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=20)),
                ("mess_reco", models.CharField(max_length=200)),
                ("mess_id", models.CharField(max_length=200)),
                ("mess_titles", models.CharField(max_length=200)),
                ("mess_dates", models.CharField(max_length=200)),
                ("dates", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Members",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
                ("nicknames", models.CharField(max_length=20)),
                ("telnos", models.CharField(max_length=20)),
                ("dates", models.CharField(max_length=20)),
            ],
        ),
    ]
